### PR TITLE
Catchup to python-herald schema. Plus lots of refactoring.

### LINKED ISSUE #46: Bring herald/db/prefixes.go up to date with new tables
Latest tables in (python) hub:

https://github.com/lbryio/hub/blob/4845b9224842e6800808aa1860330b34929b06ae/hub/db/common.py#L50

```
    channel_count = b'Z'
    support_amount = b'a'
    block_tx = b'b'
    trending_notifications = b'c'
    mempool_tx = b'd'
    touched_hashX = b'e'
    hashX_status = b'f'
    hashX_mempool_status = b'g'
```

Latest tables in herald.go:

https://github.com/lbryio/herald.go/blob/8b4b27bdb95ed899a055a9c0ebd8f10e7ca4b5e6/db/prefixes/prefixes.go#L61

```
	ChannelCount  = 'Z'
	SupportAmount = 'a'
	BlockTXs      = 'b'
```

### PR DESCRIPTION
**Pull request by moodyjon**
Fixes #46

Still debugging a test. Need to add test data for new tables.

### CODE REVIEW

**Comment by moodyjon** [comment]
I have testdata f.csv and g.csv, but currently can't "git add" them as there is an issue with case-insensitivity on MacOS.

**Comment by lothropgauss** [comment]
> I have testdata f.csv and g.csv, but currently can't "git add" them as there is an issue with case-insensitivity on MacOS.

Do you have access to a linux vps or something that you can commit those on?

**Comment by lothropgauss** [comment]
Also, I don't think we want to commit that .DS_Store file.

**Comment by moodyjon** [comment]
> > I have testdata f.csv and g.csv, but currently can't "git add" them as there is an issue with case-insensitivity on MacOS.
> 
> Do you have access to a linux vps or something that you can commit those on?

I had moved the working dir to a special case-sensitive volume a while back once I discovered the issue.
What remained to be done was changing the .git/config to contain `core.ignorecase = false`
Test data is there now.

**Comment by moodyjon** [comment]
> > I have testdata f.csv and g.csv, but currently can't "git add" them as there is an issue with case-insensitivity on MacOS.
> 
> Do you have access to a linux vps or something that you can commit those on?

I had moved the working dir to a special case-sensitive volume a while back once I discovered the issue.
What remained to be done was changing the .git/config to contain `core.ignorecase = false`
Test data is there now.

**Pull request merged**
